"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true
console_title_template = ' {{ .Folder }} :: {{if .Root}}Admin{{end}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    style = 'plain'
    template = '{{.Icon}} '
    type = 'os'

  [[blocks.segments]]
    type = 'path'
    foreground = 'p:moonstone'
    style = 'plain'
    template = ' {{ .Path }}'
    Text = ''
    Duration = 0
    NameLength = 0
    
    [blocks.segments.properties]
      home_icon = '~'
      style = 'mixed'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:khaki{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0)}}p:sky{{ end }}', '{{ if gt .Ahead 0 }}p:munsell{{ end }}', '{{ if gt .Behind 0 }}p:moonstone{{ end }}']
    foreground = 'p:khaki'
    template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_status = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    template = ' '
    background = ''
    foreground = 'p:poppy'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    template = ' {{ .Full }} '
    background = ''
    foreground = 'p:pistachio'

  [[blocks.segments]]
    type = 'go'
    style = 'plain'
    template = 'ﳑ {{ .Full}} '
    background = ''
    foreground = 'p:sky'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:mountbatten'
    template = '</> {{ .FormattedMs }} '

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    template = ' {{ .CurrentDate | date .Format }}'
    background = ''
    foreground = 'p:rose'
    
    [blocks.segments.properties]
      threshold = 500

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '❯'
    background = ''
    foreground = 'p:arylide'

[transient_prompt]
  template = '➜ '
  background = 'p:terminal_bg'
  foreground = 'p:gold'

[secondary_prompt]
  template = '➜ '
  background = 'transparent'
  foreground = 'p:gold'

[palette]
  teal = '#467E86'
  munsell = '#5396A2'
  moonstone = '#64A4B0'
  sky = '#86B8C1'
  light_blue = '#A1C8CE'
  terminal_bg = '#272229'
  eggplant = '#745869'
  mountbatten = '#8C697E'
  pink = '#9F7F92'
  rose = '#DAC2D1'
  asparagus = '#7CAE50'
  olivine = '#8CB865'
  pistachio = '#96BF73'
  persian = '#C6362C'
  poppy = '#D34136'
  jasper = '#D75147'
  indian = '#DA6058'
  citrine = '#E9D439'
  arylide = '#EDDC5A'
  flax = '#F1E37E'
  vanilla = '#F5EBA3'
  satin = '#A6983A'
  gold = '#BFB04A'
  citron = '#D5CB86'
  battleship = '#908D75'
  khaki = '#A4A28E'
  ash = '#B6B5A4'
  timberwolf = '#C9C8BB'
  platinum = '#E4E3DD'
  white_smoke = '#F6F6F4'
  

